# 하나은행 환율정보 수집하고 DB에 자동으로 저장하기_수집자동화

In [2]:
import requests
import pandas as pd
import time
from datetime import datetime

In [ ]:
#ajax=true,tmpInqStrDt=2026-01-29,pbldDvCd=3,inqStrDt=20260129,inqKindCd=1,requestTarget=searchContentDiv

In [3]:
# 하나은행 현재 환율 페이지 내부 데이터까지 다 나오는 html 파일 잘 가지고 옴
# f12-network-왼쪽파일 클릭하고-header(=url), payload

url="https://www.kebhana.com/cms/rate/wpfxd651_01i_01.do"
payload=dict(ajax="true",tmpInqStrDt='2026-01-27',pbldDvCd=0,inqStrDt='20260127',
             inqKindCd=1,requestTarget='searchContentDiv')
r=requests.get(url, params=payload)
df=pd.read_html(r.text)[0]
df.insert(0,'날짜','2026-01-27')
df

C:\Users\a\AppData\Local\Temp\ipykernel_12164\2333866393.py:8: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df=pd.read_html(r.text)[0]

            날짜               통화       현찰                              송금  \
                             통화     사실 때            파실 때            보낼 때
                             통화       환율 Spread       환율 Spread     보낼 때
0   2026-01-27           미국 USD  1460.62   1.75  1410.38   1.75  1449.50
1   2026-01-27     일본 JPY (100)   959.04   1.75   926.06   1.75   951.78
2   2026-01-27           유로 EUR  1762.95   1.99  1694.17   1.99  1745.84
3   2026-01-27           중국 CNY   217.44   5.00   196.74   5.00   209.16
4   2026-01-27           홍콩 HKD   187.68   1.97   180.44   1.97   185.90
5   2026-01-27           태국 THB    48.75   5.00    43.65   6.00    46.89
6   2026-01-27           대만 TWD    52.09  13.10    41.46  10.00    46.56
7   2026-01-27          필리핀 PHP    26.81  10.00    22.39   8.20    24.62
8   2026-01-27         싱가포르 SGD  1161.49   1.99  1116.17   1.99  1150.21
9   2026-01-27           호주 AUD  1026.03   1.97   986.39   1.97  1016.27
10  2026-01-27    베트남 VND (100)     6.14  11.80     4.86  11.80     5.55
11  2026-01-27           영국 GBP  2026.67   1.97  1948.37   1.97  2007.39
12  2026-01-27          캐나다 CAD  1078.21   1.97  1036.55   1.97  1067.95
13  2026-01-27        말레이시아 MYR   390.06   7.40   336.32   7.40   366.82
14  2026-01-27          러시아 RUB    20.61   9.50    15.54  17.50    19.48
15  2026-01-27        남아공화국 ZAR    97.68   8.00    83.22   8.00    91.53
16  2026-01-27         노르웨이 NOK   154.95   3.30   141.45   5.70   151.50
17  2026-01-27         뉴질랜드 NZD   884.48   1.97   850.32   1.97   876.07
18  2026-01-27          덴마크 DKK   239.10   3.30   218.28   5.70   233.78
19  2026-01-27          멕시코 MXN    92.61  10.50    75.01  10.50    84.64
20  2026-01-27           몽골 MNT     0.00   0.00     0.00   0.00     0.40
21  2026-01-27          바레인 BHD  4051.06   6.40  3502.80   8.00  3845.46
22  2026-01-27        방글라데시 BDT     0.00   0.00     0.00   0.00    11.89
23  2026-01-27          브라질 BRL   305.08  10.20   249.17  10.00   280.17
24  2026-01-27         브루나이 BND  1184.38   4.00  1070.51   6.00  1152.49
25  2026-01-27      사우디아라비아 SAR   406.92   6.30   356.40   6.90   386.63
26  2026-01-27         스리랑카 LKR     0.00   0.00     0.00   0.00     4.69
27  2026-01-27          스웨덴 SEK   169.09   3.30   154.36   5.70   165.32
28  2026-01-27          스위스 CHF  1922.10   1.97  1847.84   1.97  1903.81
29  2026-01-27    아랍에미리트공화국 AED   412.30   5.50   363.85   6.90   394.71
30  2026-01-27          알제리 DZD     0.00   0.00     0.00   0.00    11.24
31  2026-01-27           오만 OMR  3989.78   7.00  3467.76   7.00  3773.51
32  2026-01-27          요르단 JOD  2204.87   8.90  1862.71   8.00  2048.97
33  2026-01-27         이스라엘 ILS   510.71  10.00   427.15   8.00   469.86
34  2026-01-27          이집트 EGP     0.00   0.00     0.00   0.00    30.90
35  2026-01-27           인도 INR     0.00   0.00     0.00   0.00    15.87
36  2026-01-27  인도네시아 IDR (100)     9.43  10.00     7.73  10.00     8.66
37  2026-01-27           체코 CZK    77.37   8.50    64.90   9.00    72.09
38  2026-01-27           칠레 CLP     1.83  10.00     1.51  10.00     1.69
39  2026-01-27        카자흐스탄 KZT     0.00   0.00     0.00   0.00     2.88
40  2026-01-27          카타르 QAR     0.00   0.00     0.00   0.00   398.60
41  2026-01-27           케냐 KES     0.00   0.00     0.00   0.00    11.26
42  2026-01-27         콜롬비아 COP     0.00   0.00     0.00   0.00     0.39
43  2026-01-27         쿠웨이트 KWD  5011.66   6.50  4329.33   8.00  4752.84
44  2026-01-27         탄자니아 TZS     0.00   0.00     0.00   0.00     0.56
45  2026-01-27         튀르키예 TRY     0.00   0.00     0.00   0.00    33.42
46  2026-01-27         파키스탄 PKR     0.00   0.00     0.00   0.00     5.19
47  2026-01-27          폴란드 PLN   444.61   8.00   378.75   8.00   416.20
48  2026-01-27          헝가리 HUF     4.97   9.30     4.19   8.00     4.60
49  2026-01-27           네팔 NPR     0.00   0.00     0.00   0.00     9.89
50  2026-01-27          마카오 MOP     0.00   0.00     0.00   0.00   180.71
51  2026-01-27         캄보디아 KHR     0.00   0.00     0.00   0.00     0.36
52  2026-01-27           피지 FJD     0.00   0.00     0.00   0.00   661.78
53  2026-01-27          리비아 LYD     0.00   0.00     0.00   0.00   230.24
54  2026-01-27         루마니아 RON     0.00   0.00     0.00   0.00   342.91
55  2026-01-27          미얀마 MMK     0.00   0.00     0.00   0.00     0.68
56  2026-01-27        에티오피아 ETB     0.00   0.00     0.00   0.00     9.34
57  2026-01-27       우즈베키스탄 UZS     0.00   0.00     0.00   0.00     0.12

            외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
       받을 때 외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
       받을 때 외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
0   1421.50   1419.30  1435.50   5.52417  1.0000
1    933.32    932.67   942.55   2.83136  0.6566
2   1711.28   1709.40  1728.56   3.93400  1.2042
3    205.02      0.00   207.09   3.78500  0.1443
4    182.22    182.00   184.06   4.93433  0.1282
5     45.97     45.94    46.43   3.28333  0.0323
6     45.56      0.00    46.06   3.59266  0.0321
7     24.14      0.00    24.38   6.74300  0.0170
8   1127.45   1126.52  1138.83   3.32500  0.7933
9    996.15    994.59  1006.21   5.67700  0.7009
10     5.45      0.00     5.50   9.19833  0.0038
11  1967.65   1964.45  1987.52   5.89200  1.3845
12  1046.81   1045.57  1057.38   4.24200  0.7366
13   359.56      0.00   363.19   4.96166  0.2530
14    18.18      0.00    18.83   2.97500  0.0131
15    89.37      0.00    90.45   8.56266  0.0630
16   148.50    148.26   150.00   5.93133  0.1045
17   858.73    857.69   867.40   4.39166  0.6042
18   229.16    228.93   231.47   3.71700  0.1612
19    82.98      0.00    83.81   9.24200  0.0584
20     0.40      0.00     0.40  13.47500  0.0003
21  3769.32   3761.85  3807.39   7.07033  2.6523
22    11.61      0.00    11.75  12.46090  0.0082
23   273.53      0.00   276.85  15.09500  0.1929
24  1125.17      0.00  1138.83   3.32500  0.7933
25   378.99    378.30   382.81   6.57500  0.2667
26     4.59      0.00     4.64  11.34833  0.0032
27   162.06    161.89   163.69   3.88900  0.1140
28  1866.13   1865.05  1884.97   2.06400  1.3131
29   386.91    386.37   390.81   5.07500  0.2722
30    10.98      0.00    11.11   7.22500  0.0077
31  3684.03      0.00  3728.77   4.27500  2.5975
32  2000.39      0.00  2024.68   7.86000  1.4104
33   458.72      0.00   464.29   6.56500  0.3234
34    30.18      0.00    30.54   7.22500  0.0213
35    15.51      0.00    15.69   7.94600  0.0109
36     8.50      8.49     8.58   6.86666  0.0060
37    70.53      0.00    71.31   5.30500  0.0497
38     1.65      0.00     1.67   5.44400  0.0012
39     2.82      0.00     2.85  19.97500  0.0020
40   389.16      0.00   393.88   3.35500  0.2744
41    11.00      0.00    11.13   9.58166  0.0078
42     0.39      0.00     0.39   2.97500  0.0003
43  4658.74   4652.07  4705.79   5.10866  3.2782
44     0.56      0.00     0.56  10.82433  0.0004
45    32.70      0.00    33.06  36.96166  0.0230
46     5.07      0.00     5.13  18.37500  0.0036
47   407.16      0.00   411.68   6.38466  0.2868
48     4.50      0.00     4.55   8.29766  0.0032
49     9.67      0.00     9.78   2.97500  0.0068
50   176.43      0.00   178.57   4.93433  0.1244
51     0.36      0.00     0.36   2.97500  0.0003
52   646.10      0.00   653.94   1.97500  0.4555
53   224.78      0.00   227.51   2.97500  0.1585
54   335.45      0.00   339.18   7.77233  0.2363
55     0.68      0.00     0.68   1.97500  0.0005
56     9.12      0.00     9.23   2.97500  0.0064
57     0.12      0.00     0.12  17.47500  0.0001

In [12]:
# 하나은행 환율 수집 함수로 만들어주기
def exrate_get(ymd_dash, ymd):
    url="https://www.kebhana.com/cms/rate/wpfxd651_01i_01.do"
    payload=dict(ajax="true",tmpInqStrDt=ymd_dash,pbldDvCd=0,inqStrDt=ymd,
                 inqKindCd=1,requestTarget='searchContentDiv')
    r=requests.get(url, params=payload)
    df=pd.read_html(r.text)[0]
    df.insert(0,'날짜',ymd_dash)
    return df

# 날짜 생성하고 데이터 수집하기

In [13]:
# 위에서 만들어준 함수 추가해줌 - 23일~28일 환율 데이터 모임
result=[]
for date in list(pd.date_range("2026-01-28", "2026-01-23", freq='-1B')): # 거꾸로 주는 옵션
    ymd_dash, ymd=date.strftime("%Y-%m-%d"), date.strftime("%Y%m%d")
    print(ymd_dash, ymd)
    data=exrate_get(ymd_dash, ymd)
    result.append(data)
final_result=pd.concat(result)
final_result

2026-01-28 20260128

C:\Users\a\AppData\Local\Temp\ipykernel_12164\2287788984.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df=pd.read_html(r.text)[0]

2026-01-27 20260127

C:\Users\a\AppData\Local\Temp\ipykernel_12164\2287788984.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df=pd.read_html(r.text)[0]

2026-01-26 20260126

C:\Users\a\AppData\Local\Temp\ipykernel_12164\2287788984.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df=pd.read_html(r.text)[0]

2026-01-23 20260123

C:\Users\a\AppData\Local\Temp\ipykernel_12164\2287788984.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df=pd.read_html(r.text)[0]

            날짜            통화       현찰                              송금  \
                          통화     사실 때            파실 때            보낼 때
                          통화       환율 Spread       환율 Spread     보낼 때
0   2026-01-28        미국 USD  1458.58   1.75  1408.42   1.75  1447.50
1   2026-01-28  일본 JPY (100)   950.90   1.75   918.20   1.75   943.70
2   2026-01-28        유로 EUR  1747.99   1.99  1679.79   1.99  1731.02
3   2026-01-28        중국 CNY   216.77   5.00   196.13   5.00   208.51
4   2026-01-28        홍콩 HKD   187.35   1.97   180.13   1.97   185.57
..         ...           ...      ...    ...      ...    ...      ...
53  2026-01-23       리비아 LYD     0.00   0.00     0.00   0.00   231.46
54  2026-01-23      루마니아 RON     0.00   0.00     0.00   0.00   341.48
55  2026-01-23       미얀마 MMK     0.00   0.00     0.00   0.00     0.69
56  2026-01-23     에티오피아 ETB     0.00   0.00     0.00   0.00     9.42
57  2026-01-23    우즈베키스탄 UZS     0.00   0.00     0.00   0.00     0.12

            외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
       받을 때 외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
       받을 때 외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
0   1419.50   1417.31  1433.50   5.52434  1.0000
1    925.40    924.75   934.55   2.83136  0.6519
2   1696.76   1694.90  1713.89   3.91400  1.1956
3    204.39      0.00   206.45   3.79947  0.1440
4    181.91    181.69   183.74   4.92233  0.1282
..      ...       ...      ...       ...     ...
53   225.98      0.00   228.72   2.97500  0.1572
54   334.06      0.00   337.77   7.78300  0.2321
55     0.69      0.00     0.69   1.97500  0.0005
56     9.20      0.00     9.31   2.97500  0.0064
57     0.12      0.00     0.12  17.47500  0.0001

[232 rows x 12 columns]

In [14]:
# 컬럼명 출력 - 리스트 형태로 나옴
final_result.columns

MultiIndex([(       '날짜',          '',          ''),
            (       '통화',        '통화',        '통화'),
            (       '현찰',      '사실 때',        '환율'),
            (       '현찰',      '사실 때',    'Spread'),
            (       '현찰',      '파실 때',        '환율'),
            (       '현찰',      '파실 때',    'Spread'),
            (       '송금',      '보낼 때',      '보낼 때'),
            (       '송금',      '받을 때',      '받을 때'),
            ('외화 수표 파실때', '외화 수표 파실때', '외화 수표 파실때'),
            (   '매매 기준율',    '매매 기준율',    '매매 기준율'),
            (    '환가 료율',     '환가 료율',     '환가 료율'),
            (   '미화 환산율',    '미화 환산율',    '미화 환산율')],
           )

In [15]:
final_result[final_result[(       '통화',        '통화',        '통화')]=='미국 USD']
# 미국 것만 필터링돼서 나옴 -> 수집 제대로 되는 중암

           날짜      통화       현찰                             송금          \
                   통화     사실 때            파실 때           보낼 때    받을 때
                   통화       환율 Spread       환율 Spread    보낼 때    받을 때
0  2026-01-28  미국 USD  1458.58   1.75  1408.42   1.75  1447.5  1419.5
0  2026-01-27  미국 USD  1460.62   1.75  1410.38   1.75  1449.5  1421.5
0  2026-01-26  미국 USD  1473.34   1.75  1422.66   1.75  1462.1  1433.9
0  2026-01-23  미국 USD  1480.76   1.75  1429.84   1.75  1469.5  1441.1

  외화 수표 파실때  매매 기준율    환가 료율 미화 환산율
  외화 수표 파실때  매매 기준율    환가 료율 미화 환산율
  외화 수표 파실때  매매 기준율    환가 료율 미화 환산율
0   1417.31  1433.5  5.52434    1.0
0   1419.30  1435.5  5.52417    1.0
0   1431.68  1448.0  5.52140    1.0
0   1438.87  1455.3  5.52259    1.0

# 멀티인덱스 컬럼명 단순화하기
- 위의 표 컬럼명 보기 불편함 -> 단순화해주기
- 경우 여러 개 있음
- 0 != 1 == 2 (예: '날짜'!= ''== '')
- 0 != 1 != 2
- 0 == 1 == 2

In [ ]:
# 컬럼명 출력 - 리스트 형태로 나옴
final_result.columns

In [14]:
# 컬럼명 평탄화 함수
# 정보 딕셔너리로 정리 후, 함수로 만들기

def flatten_cols(df):
    
    new_cols={}
    for col in df.columns: # 컬럼 한 줄씩
        if col[0]!=col[1]==col[2]:
            if col[1]=="":
                new_cols[col]=col[0]
            else:
                new_cols[col]=col[0]+"_"+col[1].replace(" ","_")
        elif col[0]!=col[1]!=col[2]:
            new_cols[col]= " ".join(col).replace(" ","_")
        elif col[0]==col[1]==col[2]:
            new_cols[col]=col[0].replace(" ","_")

    return new_cols

In [24]:
flatten_cols(final_result)

{('날짜', '', ''): '날짜',
 ('통화', '통화', '통화'): '통화',
 ('현찰', '사실 때', '환율'): '현찰_사실_때_환율',
 ('현찰', '사실 때', 'Spread'): '현찰_사실_때_Spread',
 ('현찰', '파실 때', '환율'): '현찰_파실_때_환율',
 ('현찰', '파실 때', 'Spread'): '현찰_파실_때_Spread',
 ('송금', '보낼 때', '보낼 때'): '송금_보낼_때',
 ('송금', '받을 때', '받을 때'): '송금_받을_때',
 ('외화 수표 파실때', '외화 수표 파실때', '외화 수표 파실때'): '외화_수표_파실때',
 ('매매 기준율', '매매 기준율', '매매 기준율'): '매매_기준율',
 ('환가 료율', '환가 료율', '환가 료율'): '환가_료율',
 ('미화 환산율', '미화 환산율', '미화 환산율'): '미화_환산율'}

In [25]:
new_cols_dict=flatten_cols(final_result)

In [29]:
for col in final_result:
    #print(new_cols_dict) # 변화된 부분만 나옴

SyntaxError: incomplete input (3817071785.py, line 2)

In [30]:
new_cols= [new_cols_dict[col] for col in final_result]
new_cols # 새로운 컬럼명 리스트로 만들어줌

['날짜',
 '통화',
 '현찰_사실_때_환율',
 '현찰_사실_때_Spread',
 '현찰_파실_때_환율',
 '현찰_파실_때_Spread',
 '송금_보낼_때',
 '송금_받을_때',
 '외화_수표_파실때',
 '매매_기준율',
 '환가_료율',
 '미화_환산율']

In [31]:
final_result.columns=new_cols
final_result

,날짜,통화,현찰_사실_때_환율,현찰_사실_때_Spread,현찰_파실_때_환율,현찰_파실_때_Spread,송금_보낼_때,송금_받을_때,외화_수표_파실때,매매_기준율,환가_료율,미화_환산율
0,2026-01-28,미국 USD,1458.58,1.75,1408.42,1.75,1447.50,1419.50,1417.31,1433.50,5.52434,1.0000
1,2026-01-28,일본 JPY (100),950.90,1.75,918.20,1.75,943.70,925.40,924.75,934.55,2.83136,0.6519
2,2026-01-28,유로 EUR,1747.99,1.99,1679.79,1.99,1731.02,1696.76,1694.90,1713.89,3.91400,1.1956
3,2026-01-28,중국 CNY,216.77,5.00,196.13,5.00,208.51,204.39,0.00,206.45,3.79947,0.1440
4,2026-01-28,홍콩 HKD,187.35,1.97,180.13,1.97,185.57,181.91,181.69,183.74,4.92233,0.1282
...,...,...,...,...,...,...,...,...,...,...,...,...
53,2026-01-23,리비아 LYD,0.00,0.00,0.00,0.00,231.46,225.98,0.00,228.72,2.97500,0.1572
54,2026-01-23,루마니아 RON,0.00,0.00,0.00,0.00,341.48,334.06,0.00,337.77,7.78300,0.2321
55,2026-01-23,미얀마 MMK,0.00,0.00,0.00,0.00,0.69,0.69,0.00,0.69,1.97500,0.0005
56,2026-01-23,에티오피아 ETB,0.00,0.00,0.00,0.00,9.42,9.20,0.00,9.31,2.97500,0.0064
57,2026-01-23,우즈베키스탄 UZS,0.00,0.00,0.00,0.00,0.12,0.12,0.00,0.12,17.47500,0.0001

# 날짜 데이터 생성 후 데이터 수집하고 column명 변환해서 DB에 저장하기

In [1]:
from io import StringIO
import requests
import pandas as pd
import time
from datetime import datetime
from dbio import to_db

In [2]:
# 하나은행 환율 수집 함수
def exrate_get(ymd_dash, ymd):
    url="https://www.kebhana.com/cms/rate/wpfxd651_01i_01.do"
    payload=dict(ajax="true",tmpInqStrDt=ymd_dash,pbldDvCd=0,inqStrDt=ymd,
                 inqKindCd=1,requestTarget='searchContentDiv')
    r=requests.get(url, params=payload)
    df=pd.read_html(StringIO(r.text))[0]
    df.insert(0,'날짜',ymd_dash)
    return df

In [11]:
#컬럼명 평탄화 함수
def flatten_cols(df):
    
    new_cols={}
    for col in df.columns: # 컬럼 한 줄씩
        if col[0]!=col[1]==col[2]:
            if col[1]=="":
                new_cols[col]=col[0]
            else:
                new_cols[col]=col[0]+"_"+col[1].replace(" ","_")
        elif col[0]!=col[1]!=col[2]:
            new_cols[col]= " ".join(col).replace(" ","_")
        elif col[0]==col[1]==col[2]:
            new_cols[col]=col[0].replace(" ","_")

    return new_cols

In [12]:
result=[]
for date in list(pd.date_range("2026-01-28", "2026-01-23", freq='-1B')): # 거꾸로 주는 옵션
    ymd_dash, ymd=date.strftime("%Y-%m-%d"), date.strftime("%Y%m%d")
    print(ymd_dash, ymd)
    data=exrate_get(ymd_dash, ymd)
    result.append(data)
final_result=pd.concat(result)

# 수집된 데이터프레임 컬럼명 평탄화 하기
new_cols_dict=flatten_cols(final_result)
new_cols= [new_cols_dict[col] for col in final_result]
final_result.columns=new_cols
final_result

# dbio 함수로 결과 DB에 저장하기
to_db("exchange_rage_data","exchange_rate", final_result)

2026-01-28 20260128
2026-01-27 20260127
2026-01-26 20260126
2026-01-23 20260123
exchange_rage_data 데이터베이스 확인/생성 완료
exchange_rage_data.exchange_rate 데이터 저장 완료(append)

# 1일 데이터 수집 후 바로 DB 저장하기

In [15]:
# 하루치 수집하고 바로바로 DB에 저장하기

for date in list(pd.date_range("2026-01-28", "2026-01-23", freq='-1B')): # 거꾸로 주는 옵션
    ymd_dash, ymd=date.strftime("%Y-%m-%d"), date.strftime("%Y%m%d")
    data=exrate_get(ymd_dash, ymd)

    # 수집된 데이터프레임 컬럼명 평탄화 하기
    new_cols_dict=flatten_cols(data)
    new_cols= [new_cols_dict[col] for col in data]
    data.columns=new_cols
    # dbio 함수로 결과 DB에 저장하기
    to_db("exchange_rage_data","exchange_rate", data)
    time.sleep(2)

exchange_rage_data 데이터베이스 확인/생성 완료
exchange_rage_data.exchange_rate 데이터 저장 완료(append)
exchange_rage_data 데이터베이스 확인/생성 완료
exchange_rage_data.exchange_rate 데이터 저장 완료(append)
exchange_rage_data 데이터베이스 확인/생성 완료
exchange_rage_data.exchange_rate 데이터 저장 완료(append)
exchange_rage_data 데이터베이스 확인/생성 완료
exchange_rage_data.exchange_rate 데이터 저장 완료(append)

# 오늘 날짜 환율 정보 수집하고 DB 저장하기

In [ ]:
from io import StringIO
import requests
import pandas as pd
import time
from datetime import datetime
from dbio import to_db

In [ ]:
# 하나은행 환율 수집 함수
def exrate_get(ymd_dash, ymd):
    url="https://www.kebhana.com/cms/rate/wpfxd651_01i_01.do"
    payload=dict(ajax="true",tmpInqStrDt=ymd_dash,pbldDvCd=0,inqStrDt=ymd,
                 inqKindCd=1,requestTarget='searchContentDiv')
    r=requests.get(url, params=payload)
    df=pd.read_html(StringIO(r.text))[0]
    df.insert(0,'날짜',ymd_dash)
    return df

In [ ]:
#컬럼명 평탄화 함수
def flatten_cols(df):
    
    new_cols={}
    for col in df.columns: # 컬럼 한 줄씩
        if col[0]!=col[1]==col[2]:
            if col[1]=="":
                new_cols[col]=col[0]
            else:
                new_cols[col]=col[0]+"_"+col[1].replace(" ","_")
        elif col[0]!=col[1]!=col[2]:
            new_cols[col]= " ".join(col).replace(" ","_")
        elif col[0]==col[1]==col[2]:
            new_cols[col]=col[0].replace(" ","_")

    return new_cols

# 오늘 날짜만 데이터 수집하기

In [20]:
# 오늘 날짜 반환 함수
def t_day():
    today=datetime.today()
    date=today.date() # 날짜만 나옴
    ymd_dash, ymd = date.strftime("%Y-%m-%d"), date.strftime("%Y%m%d")
    return ymd_dash, ymd

In [23]:
# t_day() 함수로 오늘 날짜 만든 후 데이터 수집

#data = exrate_get(*t_day()) # * : 내부 내용이 하나씩 풀어져서 들어감

ymd_dash, ymd=t_day()
data= exrate_get(ymd_dash, ymd)

# 수집된 데이터프레임 컬럼명 평탄화 하기
new_cols_dict=flatten_cols(data)
new_cols= [new_cols_dict[col] for col in data]
data.columns=new_cols

# dbio 함수로 결과 DB에 저장하기
to_db("exchange_rage_data","exchange_rate", data)

print(f"{ymd_dash} 환율 데이터 수집 및 저장 완료")

exchange_rage_data 데이터베이스 확인/생성 완료
exchange_rage_data.exchange_rate 데이터 저장 완료(append)
2026-01-29 환율 데이터 수집 및 저장 완료